### ISSUE TITLE
Export to CSV functionality

### ISSUE THREAD

**Issue by yitjob** [Holt59/datatable#18]
Great job!
It would be desirable to have the ability to export to csv at least, and to pdf and xslx perhaps, all data on the datatable as the jQuery DataTables plugin.

**Comment by Holt59** [comment]
Hi,

Exporting all data (or the filtered data) to CSV should be possible and not to hard to implement so I will probably give it a try.

Exporting to PDF / XLS(X) without a third party library may be harder to do, I'll see if something is available.
