### ISSUE TITLE
add filter options automatically in all thead

### ISSUE THREAD

**Issue by Pravinda** [Holt59/datatable#21]
Can we add a filter in all 'th' automatically similarly as we are doing for sorting?
 $('#example-table1').datatable({
      pageSize: 20,
      **_sort: '*',_**
      filters: [true, true, true],
      filterText: 'Type to filter... '
    });

**Comment by Holt59** [comment]
There is currently no way to do this - This could be added quite easily though.

**Comment by Holt59** [comment]
You can test it: https://github.com/Holt59/datatable/tree/fix-issue-21
