### ISSUE TITLE
Sort Date format d/m/Y

### ISSUE THREAD

**Issue by loscar20** [Holt59/datatable#24]
Hi!!,

How to order a date field with format d/m/Y???
I have tried but I can not get it to order
I use Jquery and the third column is of the date type.

Thanks!!!

**Comment by Holt59** [comment]
How do you create the datable? Do you use an existing table or  JSON array (or something else)?

If the data inside the datatable are of `Date` type (not string), then setting using the `sort` option should be sufficient.

**Comment by loscar20** [comment]
I used an existing table, created dynamically with php.
I have tried with format 'Y/m/d', works and it orders. But I need show in format 'd/m/Y'.
Thanks.

**Comment by Holt59** [comment]
You can try to use the `dataTypes` options:

```js
$('#my-table').datatable({
    dataTypes: [true, true, 'date', true, ..., true]
});
```

You need to fill `dataTypes` with `true` for all other columns. Using `'date'`, the plugin will try to convert your string to:

```js
new Date(/* initial string */);
```

If the default converter does not work, you can use a custom one:

```js
function customDate(s) {
    // Here you can do whatever you want to convert your string to a date
    var dmy = s.split('/');
    return new Date(dmy[2], dmy[1], dmy[0]);
}

$('#my-table').datatable({
    dataTypes: [true, true, customDate, true, ..., true]
});
```

**Comment by loscar20** [comment]
Works perfectly, but now it shows me the date in long format
![image](https://user-images.githubusercontent.com/29570490/27380075-1832c73a-567e-11e7-8041-b90bcd5d8331.png)
And if I try to change it with the .toLocaleDateString ("es-ES") function
`function customDate(s) {
			    // Here you can do whatever you want to convert your string to a date
			    var dmy = s.split('/');
			    var options = { year: "numeric", month: "2-digit", day: "2-digit", hour12:"false"};
			    return new Date(dmy[2], dmy[1], dmy[0]).toLocaleString('es-ES', options);
			}`
Not reorder it.
![image](https://user-images.githubusercontent.com/29570490/27380213-8f5952ca-567e-11e7-8e5c-fb4dde4cfa1b.png)

With the dataTypes: [true, true, 'date'...... Exactly the same happens, show the format long.

**Comment by Holt59** [comment]
You want to internally store date as `Date` and then process the output, so you need to use the `lineFormat` option:

```js
function customDate(s) {
    // Here you can do whatever you want to convert your string to a date
    var dmy = s.split('/');
    return new Date(dmy[2], dmy[1], dmy[0]);
}

$('#my-table').datatable({
    dataTypes: [true, true, customDate, true, ..., true],
    lineFormat: function(id, data) {
        var res = $('tr');
        for (var key in data) {
            if (data.hasOwnProperty(key)) {
                var value = data[key];
                if (value instanceof Date) {
                    value = toLocaleString('es-ES');
                }
                res.append('<td>' + value + '</td>');
            }
        }
    }
});
```

**Comment by loscar20** [comment]
ok, thanks!!!! Now works perfectly. 

Thanks so much!!, regards.
