### ISSUE TITLE
IE 11: Pagination and filter not working correctly

### ISSUE THREAD

**Issue by Sebijk** [Holt59/datatable#28]
Its not working. When i sort tables, then it show pagination but filter still not present.

Screenshot:
![grafik](https://user-images.githubusercontent.com/13401679/33142088-8dbba1a6-cfb5-11e7-8676-af13081c3a09.png)

Tested with: IE 11 under Win 7

**Comment by Holt59** [comment]
Thanks for the feedback, I've fixed it with commit d58055beb25c49fc77f1477b713d1abd6c5d0e00 and I have updated the documentation accordingly.

Feel free to close the issue if the problem is solved!

**Comment by Sebijk** [comment]
Thanks, its working now.
