### ISSUE TITLE
Not working on my project :(

### ISSUE THREAD

**Issue by tonyng3101** [Holt59/datatable#31]
I use it in my project. But it not work.
`<table class="table table-hover" id="MyTable">
			<thead class="thead-dark">
				<tr>
					<th scope="col">STT</th>
					<th scope="col">Tên lớp học</th>
					<th scope="col">Số môn đang học</th>
				</tr>
			</thead>
			<tbody>
			<?php 
				$i = 1;
				foreach ($listClass as $list) {

					$id_c = $list['id_class'];
					$sql_c = "SELECT COUNT(id_sub) as num FROM relation WHERE id_class = '$id_c'";
					$query_c = $db->query($sql_c);
					while ($count_c = $query_c->fetch()) {	
			?>
				<tr>
					<td scope="row"><?php echo $i; $i++; ?></td>
					<td><a href=""><?php echo $list['name_class']; ?></a></td>
					<td><?php echo $count_c['num']; ?></td>
				</tr>
			<?php 
					}
				} 
			?>
			</tbody>
		</table>

		$(document).ready(function(){
			$('#MyTable').datatable({
			    pageSize: 15,
			    sort: '*'
			}) ;

			$('#MyTable').datatable('page', 3);
			var data = $('#MyTable').datatable('select');
			$('#MyTable').datatable('delete', function (e) {
			    return e.title.trim().length > 0;
			});
		});`

**Comment by Holt59** [comment]
What *"does not work"*? The table or one of the command? `e.title` is likely undefined since you used data from an HTML table, so you need `e[n]` where `n` is the number of the relevant column.

**Comment by tonyng3101** [comment]
The table still show. But it is not paged

**Comment by Holt59** [comment]
How many elements do you have in the table? If you have less than 15 then you won't notice a difference.

If this is not the case, I would need data to investigate. Could you send me the generated HTML table?

**Comment by tonyng3101** [comment]
It is my table now.

```
<table class="table table-hover" id="MyTable">
			<thead class="thead-dark">
				<tr>
					<th scope="col">STT</th>
					<th scope="col">Class Name</th>
					<th scope="col">Subject</th>
				</tr>
			</thead>
			<tbody>
							<tr>
					<td scope="row">1</td>
					<td><a href="">CP14</a></td>
					<td>2</td>
				</tr>
							<tr>
					<td scope="row">2</td>
					<td><a href="">CP15</a></td>
					<td>3</td>
				</tr>
							<tr>
					<td scope="row">3</td>
					<td><a href="">CP16</a></td>
					<td>2</td>
				</tr>
							<tr>
					<td scope="row">4</td>
					<td><a href="">CP17</a></td>
					<td>0</td>
				</tr>
							<tr>
					<td scope="row">5</td>
					<td><a href="">CP18</a></td>
					<td>3</td>
				</tr>
							<tr>
					<td scope="row">6</td>
					<td><a href="">CP12</a></td>
					<td>3</td>
				</tr>
			</tbody>
</table>
```


I just change pageSize to 5 but it still not work

**Comment by tonyng3101** [comment]
Did I forgot some thing?

**Comment by Holt59** [comment]
I have no issue with your table, did you:

- Add a `<div>` for paging? e.g., `<div class="paging"></div>` after the table?
- Include both `datatable.min.js` and `datatable.jquery.min.js`?

**Comment by tonyng3101** [comment]
Thanh for your help! But I still have a question. Can it use for 2 or more table in one page??
I just add an id like `$('#MyTable, #Mytable2').datatable` but it look not work!
