### ISSUE TITLE
CSS not work

### ISSUE THREAD

**Issue by tonyng3101** [Holt59/datatable#32]
I am add both `datatable.css` and  `datatable-bootstrap.css` but the style is not active for pagination

**Comment by Holt59** [comment]
You must only include the `datatable-bootstrap` file. Which version of Bootstrap are you using?

**Comment by tonyng3101** [comment]
I'm using Bootstrap 4!

**Comment by Holt59** [comment]
If you are using Bootstrap 4, you need to customize some options, in particular:

```    
pagingItemClass: 'page-item',
pagingLinkClass: 'page-link',
pagingLinkDisabledTabIndex: true
```

**Comment by tonyng3101** [comment]
Thanks you!
