### ISSUE TITLE
Filter outside the table

### ISSUE THREAD

**Issue by tonyng3101** [Holt59/datatable#34]
I wanna bring the search bar  outside the table. How can I do that?

**Comment by Holt59** [comment]
Once they have been created, you can move the filters freely using standard DOM manipulation. 

A quick example (using non-jQuery version):

```javascript
// You can retrieve the filter element the way you want, each control element used to
// filter has a data-filter attribute set to the name of the column (numeric value for
// unamed columns).
var filter element = document.querySelector('#MyTableId [data-filter="0"]');

var myContainer = /* Whatever you want. */

// You need to use DOM manipulation function so that events associated with the filter
// elements remain. E.g., don't use innerHTML.
myContainer.appendChild(filter);
```

**Comment by Holt59** [comment]
@tonyng3101 Without feedbacks from you, I am closing this. I have added a quick example to demonstrate how you can move filter elements.

If you still have trouble with this, feel free to re-open this issue.
