### ISSUE TITLE
filter is not function after apply addRows 

### ISSUE THREAD

**Issue by leehengbing** [Holt59/datatable#46]
Hi, 
I have 3 records exist in the datatable when the document is loaded. The filter and sort function is perform perfectly.
But when i try to add in a record using addRows function, i can see the record added inside the datatable but when
i try to perform filter function, it is always filter for the 3 records that is previously loaded only. And the sorting function
is broken. Any idea ?

**Comment by Holt59** [comment]
It's complicated to give you any hint without seeing how the date looks and how you call `addRows`, etc. Can you post something thrat reproduces the issue?

**Comment by leehengbing** [comment]
Hi, thanks for your reply. Already found the issues, it is because of re-declare the datatable object. 
Regards
